# Datasource 소스
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: wednesday5028@gmail.com
    password: zpoapnmapvxasumu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  thymeleaf:
    cache: false
  messages:
    basename: messages,errors
  datasource:
    url: jdbc:mysql://dancingwhale.clqa4sewjdov.ap-northeast-2.rds.amazonaws.com:3306/dancingwhale
    username: k1ng
    password: g5ph2357
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

# 세션 유지 시간 30분
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 1800
      tracking-modes: cookie
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

# 상품 이미지 업로드 경로

upload:
  postImgLocation: C:/doinggajigaji/post
  uploadPath: file:///C:/doinggajigaji/
# 리소스 업로드 경로

secretKey:
  ZVZ9QR/ED0UKkYNGUXpJqWFNfQbPUstrAaib/rWZ
accessKey:
  AKIAYGAB2ZYLGG34KDIU




